[project]
name = "win-quick-ocr"
version = "0.1.0"
description = "Quick Screenshot OCR Tool for Windows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "rapidocr-onnxruntime>=1.4.4",
    "termcolor>=2.5.0",
]
[tool.setuptools]
py-modules = []
